services:
  banktransfer:
    build:
      context: ./src
      dockerfile: banktransfer/Dockerfile
    environment:
      - KAFKA_CONNECT=kafka:9092
      - LOG_LEVEL=info # change to trace for debugging
  myaktion:
    build:
      context: ./src
      dockerfile: myaktion/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECT=mariadb:3306
      - BANKTRANSFER_CONNECT=banktransfer:9111
      - LOG_LEVEL=info # change to trace for debugging
  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myaktion
  kafka:
    image: bitnami/kafka:3.3.2
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
