apiVersion: v1
kind: Service
metadata:
  name: banktransfer
  namespace: myaktion
spec:
  type: ClusterIP
  ports:
    - port: 9111
      targetPort: 9111
      name: "grpc"
  selector:
    run: banktransfer
