apiVersion: v1
kind: Service
metadata:
  name: myaktion
  namespace: myaktion
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: "http"
  selector:
    run: myaktion
