apiVersion: v1
kind: Service
metadata:
  # reason for name mykafka: https://morioh.com/p/d1bafbd024d6
  name: mykafka
  namespace: myaktion
spec:
  type: ClusterIP
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
  selector:
    run: mykafka
