apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: myaktion
spec:
  selector:
    matchLabels:
      run: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        run: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: myaktion
