apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-env-config
  namespace: myaktion
data:
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_CFG_NODE_ID: "1"
  KAFKA_CFG_PROCESS_ROLES: "broker,controller"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://mykafka:9092"
  KAFKA_CFG_BROKER_ID: "1"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@mykafka:9093"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_KRAFT_CLUSTER_ID: "r4zt_wrqTRuT7W2NJsB_GA"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykafka
  namespace: myaktion
spec:
  selector:
    matchLabels:
      run: mykafka
  replicas: 1
  template:
    metadata:
      labels:
        run: mykafka
    spec:
      containers:
        - name: mykafka
          image: bitnami/kafka:3.3.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: kafka-env-config
